myapp/urls.py
from django.urls import path
from myapp import views
from django.conf import settings
from django.conf.urls.static import static
app_name='myapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/',views.register,name='signup'),
    path('signin/',views.user_login,name='signin'),
    path('logout/',views.user_logout,name="logout"),
    path('course/<slug:slug>/',views.course,name="cours"),
    path('course/<slug:sslug>/<slug:slugpost>/',views.course_details,name="course_details"),
    path('search/',views.search,name="search"),
    path('course/',views.allcourse,name="allcourse"),
    path('contact/',views.contact,name="contact"),
    path('blog/',views.blogapp,name="blogapp"),
    path('blog/<slug:slug>',views.blogs_detail,name="blogs_detail"),
    path('dashboard/',views.dashboard,name="dboard"),
    path('success/', views.callback, name="success"),
    path('dashboard/notification/',views.dashboard_notification,name="notify"),
    path('dashboard/purchased/', views.dashboard_purchased_course,name="purchased"),
    path('change-password/',views.password_change,name="password")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

premium/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from premium import views
app_name="premium"
urlpatterns = [
    path('',views.home,name="home"),
    path('overview/<slug:pslug>/',views.course_overview,name="overview"),
    path('overview/<slug:slug>/payment/',views.premium_course,name='premium_course'),
    # path('callback/',views.pay_sucess,name='success'),
    path('premium/<slug:course_slug>',views.preimum_course_overviews,name="premium_course_overview"),
    path('premium/<slug:course_slug>/<slug:details_slug>/',
         views.premium_course_detail, name="premium_course_details"),
    path('form-success/',views.form_success),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
# app_name="tutorial"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('money/',include('premium.urls')),
    path('quiz/',include('quizapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
Http404 = "premium.views.page_not_found_view"
handler500 = "premium.views.page_not_found"

premium/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from requests import request

# Create your models here.
class PremiumCourse(models.Model):
    course_title=models.CharField(max_length=30,help_text="Enter The Course Title At Least 10 Words")
    course_slug=models.SlugField(null=False,unique=True)
    course_about=models.CharField(max_length=100,help_text="Enter The Course Details At Least 20 Words")
    what_we_learn=RichTextField()
    course_thumbnail=models.ImageField(upload_to='static/upload/')
    course_join=models.DateTimeField(auto_now_add=True)
    course_price=models.IntegerField()
    course_discount=models.IntegerField(default=0,help_text="Enter The Discount In Percentage Like 25,75 etc.")
    is_active=models.BooleanField(default=False)
    @property
    def discount(self):
        if self.course_discount>0:
            discount_price=self.course_price-self.course_price*self.course_discount/100
        return discount_price

    def get_order(self,user):
        return self.order_set.get(user=user,status="Success")

    def __str__(self):
        return self.course_title
    
    class Meta:
        verbose_name_plural="Course"
    

class PremiumCourseDetail(models.Model):
    course_name=models.ForeignKey(PremiumCourse,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    slug=models.SlugField(null=False,unique=True)
    article=RichTextField()
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural="Course Detail"
    def __str__(self):
        return self.title

class Paymentstatus:
    SUCCESS="Success"
    PENDING="Pending"
    FAILURE="Failure"

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING,editable=False)
    course=models.ForeignKey(PremiumCourse,on_delete=models.DO_NOTHING,editable=False)
    status=models.CharField(default=Paymentstatus.PENDING,max_length=254,blank=False,null=False,editable=False)
    provider_order_id=models.CharField(("Order ID"),max_length=254,null=False,blank=False,editable=False)
    payment_id=models.CharField(max_length=254,null=False,blank=False,editable=False)
    signature_id=models.CharField(max_length=254,null=False,blank=False,editable=False)
    amount=models.IntegerField(editable=False)
    order_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class Feedback(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING,editable=False)
    course=models.ForeignKey(PremiumCourse,on_delete=models.DO_NOTHING,editable=False)
    star=models.IntegerField(editable=False)
    say_something=models.TextField(editable=False)
    date=models.DateTimeField(auto_now=True,editable=False)

class Certificate(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    course=models.ForeignKey(PremiumCourse,on_delete=models.CASCADE)
    upload=models.ImageField(upload_to='static/upload/')

premium/views.py
import json
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from premium.models import Certificate, Feedback, Order, PremiumCourse,Paymentstatus, PremiumCourseDetail
import razorpay
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from quizapp.models import Result
# Create your views here.


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

def page_not_found(request):
    return render(request, '404.html')
def home(request):
    premium=PremiumCourse.objects.filter(is_active=True)
    return render(request,"premium.html",{"premium":premium})

@login_required(login_url='myapp:signup')
def premium_course(request,slug):
    # premium=PremiumCourse.objects.get(course_slug=slug)
    premium=get_object_or_404(PremiumCourse,course_slug=slug)
    amount = premium.course_price-premium.course_price*premium.course_discount/100
    amount_paisa=amount*100
    client=razorpay.Client(auth=(settings.KEY_ID,settings.KEY_SECRET))
    razorpay_order=client.order.create(dict(amount=int(amount_paisa),currency="INR",payment_capture='1'))
    order=Order.objects.create(user=request.user,course=premium,provider_order_id=razorpay_order["id"],amount=amount)
    order.save()
    is_pay=Order.objects.filter(user=request.user,course=premium,status="Success")
    return render(request,"premiumcourse.html",{"premium":premium,'response':razorpay_order,"is_pay":is_pay})

def course_overview(request,pslug):
    purchase=get_object_or_404(PremiumCourse,course_slug=pslug)
    feedback=Feedback.objects.filter(course=purchase)
    return render(request,'overview.html',{"premium":purchase,"feedback":feedback})



@login_required(login_url="myapp:signup")
def preimum_course_overviews(request, course_slug):
    try:
        premium=PremiumCourse.objects.get(course_slug=course_slug)
    except:
        raise Http404
    try:
        premium_course=PremiumCourseDetail.objects.filter(course_name=premium)
    except PremiumCourseDetail.DoesNotExist:
        raise Http404      
    order=get_object_or_404(Order,user=request.user,course=premium,status="Success")
    return render(request,"premiumoverview.html",{'premium':order,"premium_course":premium_course})

@login_required(login_url="myapp:signup")
def premium_course_detail(request,course_slug,details_slug):
    try:
        premium=PremiumCourse.objects.get(course_slug=course_slug)
    except:
        raise Http404
    try:
        purchase=Order.objects.get(user=request.user,course=premium,status="Success")
    except:
        raise Http404
    
    try:
        premium_course=PremiumCourseDetail.objects.filter(course_name=premium)
    except:
        raise Http404
    cc=get_object_or_404(PremiumCourseDetail,slug=details_slug)
    premium_course_all=get_object_or_404(PremiumCourseDetail,slug=details_slug,course_name=premium)
    try:
        next_page = premium_course_all.get_next_by_created()
    except:
        next_page = None
    try:
        prev_page = premium_course_all.get_previous_by_created()
    except:
        prev_page = None
    f=Feedback.objects.filter(user=request.user,course=premium).exists()
    exam=Result.objects.filter(user=request.user,course=premium).exists()
    # exm=get_object_or_404(Result,user=request.user,course=premium)
    try:
        exm=Result.objects.filter(user=request.user,course=premium).first()
    except:
        print('error')
    if request.method=="POST":
        ratings=request.POST['rating']
        say_something=request.POST['say_something']
        feedback=Feedback.objects.create(course=premium,user=request.user,star=ratings,say_something=say_something)
        feedback.save()
        messages.success(request,"Thank you for your valueable feedback")
        return redirect('myapp:home')
    return render(request,"premiumcoursedetails.html",{"purchase":purchase,"premium_course":premium_course,"premium_course_all":premium_course_all,"cc":cc,"premium":premium,"next_page":next_page,"prev_page":prev_page,"f":f,"exam":exam,"exm":exm})

def form_success(request):
    return render('success.html')

templates/course.html
{% extends 'base.html' %}
{% block title %}Course | {{slugpost.course_title}}{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row my-2">
        <div class="col-sm-8">
            {{slugpost.what_we_learn | safe}}
        </div>
        <div class="col-sm-4">
            <h5>Course: {{slugpost.course_title}}</h5>

            <div class="list-group overflow-auto overflow-x-hidden" style="height:30rem">
                {% for course in course %}
                <a type="button" href="{% url 'myapp:course_details' slugpost.course_slug course.slug %}"
                    class="list-group-item my-2 shadow p-3 mb-3 bg-white rounded list-group-item-action">
                    {{course.title}}
                </a>
            {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
{% load static %}
<div class="p-md-6 mb-5 text-black rounded custom-image" style="padding:5rem">
  {% comment %} background:#dfdce3;color:black;padding:5rem; {% endcomment %}
  <div class="col-md-6 px-0">
    <h1 class="display-5 fw-bold text-white">Welcome To Online Tutorial</h1>
    <p class="lead my-3 text-black text-white">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    <p class="lead mb-0">
      <a href="{% url 'myapp:allcourse' %}" class="btn btn-warning text-white">Course</a>
      <a href="" class="btn btn-warning text-white">Explore</a></p>

    </div>
  </div>

  <!--Counter Course-->
  <section class="py-0 py-xl-5">
	<div class="container">
		<div class="row g-4">
			<!-- Counter item -->
			<div class="col-sm-6 col-xl-3">
				<div class="d-flex justify-content-center align-items-center p-4 bg-warning bg-opacity-15 rounded-3">
					<span class="display-6 lh-1 text-warning mb-0"><i class="fas fa-tv text-dark"></i></span>
					<div class="ms-4 h6 fw-normal mb-0">
						<div class="d-flex">
							<h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="10" data-purecounter-delay="200" data-purecounter-duration="0">{{total_count}}</h5>
						</div>
						<p class="mb-0">Online Courses</p>
					</div>
				</div>
			</div>
			<!-- Counter item -->
			<div class="col-sm-6 col-xl-3">
				<div class="d-flex justify-content-center align-items-center p-4 bg-primary bg-opacity-10 rounded-3">
					<span class="display-6 lh-1 text-blue mb-0"><i class="fas fa-user-tie"></i></span>
					<div class="ms-4 h6 fw-normal mb-0">
						<div class="d-flex">
							<h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="200" data-purecounter-delay="200" data-purecounter-duration="0">{{user_count}}</h5>
							<span class="mb-0 h5">+</span>
						</div>
						<p class="mb-0">Total Student</p>
					</div>
				</div>
			</div>
			<!-- Counter item -->
			<div class="col-sm-6 col-xl-3">
				<div class="d-flex justify-content-center align-items-center p-4 bg-success bg-opacity-10 rounded-3">
					<span class="display-6 lh-1 text-purple mb-0"><i class="fas fa-user-graduate"></i></span>
					<div class="ms-4 h6 fw-normal mb-0">
						<div class="d-flex">
							<h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="60" data-purecounter-delay="200" data-purecounter-duration="0">{{course_count}}</h5>
						</div>
						<p class="mb-0">Free Course</p>
					</div>
				</div>
			</div>
			<!-- Counter item -->
			<div class="col-sm-6 col-xl-3">
				<div class="d-flex justify-content-center align-items-center p-4 bg-info bg-opacity-10 rounded-3">
					<span class="display-6 lh-1 text-info mb-0"><i class="fas fa-certificate text-dark"></i></span>
					<div class="ms-4 h6 fw-normal mb-0">
						<div class="d-flex">
							<h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="6" data-purecounter-delay="300" data-purecounter-duration="0">{{premium_count}}</h5>
						</div>
						<p class="mb-0">Certified Courses</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--Counter Course End-->
            <div class="container">
              <div class="row">
                <div class="col-md-6 mx-auto">
                  <h2 class="text-center fs-1 mx-auto">Premium Course</h2>
                </div>
              </div>
            </div>
            <div class="container">
            <div id="new" class="tab-pane fade show p-0 active">
              <div class="container">
                <div class="row g-4">
                  {% for premium in premium %}
                    <div class="col-lg-4 col-md-6 shadow">
                        <div class="product-item">
                            <div class="position-relative bg-light">
                                <img class="img-fluid w-100" src="{{premium.course_thumbnail.url}}" alt="">
                                <div class="bg-danger rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">-{{premium.course_discount}}%</div>
                            </div>
                            <div class="text-center p-4">
                                <h4 class="d-block  mb-2" href="">{{premium.course_title}}</h4>
                                <h6>{{premium.course_about}}</h6>
                                <span class="text-primary me-1">${{premium.discount}}</span>
                                <span class="text-body text-decoration-line-through">Rs.{{premium.course_price}}</span>
                            </div>
                            <div class="d-flex border-top">
                                    <a class="text-decoration-none p-3 text-center mx-auto" href="{% url 'premium:overview' premium.course_slug %}"><i class="fa fa-eye text-primary me-2"></i>View detail</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    </div>
                    </div>
                    </div>
                    </div>

                    <div class="col-12 text-center my-4">
                        <a class="btn btn-primary rounded-pill py-3 px-5 text-white" href="{% url 'premium:home' %}">Browse More</a>
                    </div>
<!-- ---------------------------------------------------------freee-------------------------------------- -->
  <!--
  
  -->
<div class="container mx-auto">
<h2 class="text-center fs-1 mx-auto">Free Course</h2>
<p class="mb-0 text-center mx-auto">Explore couses with most helpful tools.</p>
<div class="d-inline-flex flex-wrap">
{% for course in course %}
<div class="d-flex mx-4 shadow-lg card mt-2 rounded-2x1" style="width: 19rem;">
  <img src="{{course.course_thumbnail.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{course.course_title}}</h5>
    <p class="card-text">{{course.course_about}}</p>
    <a href="{% url 'myapp:cours' course.course_slug %}" class="btn btn-primary text-white">View More</a>
  </div>
</div>
  {% endfor %}
</div>
  </div>
<div class="col-12 text-center my-4">
                        <a class="btn btn-primary rounded-pill py-3 px-5 text-white" href="{% url 'myapp:allcourse' %}">Browse More</a>
                    </div>

<!--Carousel start -->
<div id="carouselExample" class="carousel slide " data-mdb-interval="false">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/static/image/BN3.png" class="d-block w-100" alt="BN3">
    </div>
    <div class="carousel-item" data-mdb-interval="2000">
      <img src="/static/image/BN2.png" class="d-block w-100" alt="BN2">
    </div>
    <div class="carousel-item">
      <img src="/static/image/BN1.png" class="d-block w-100" alt="BN1">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
                 
   <div class="container-fluid my-4">
    <div class="row">
			<div class="col-12">
				<div class="short-row p-4 p-sm-5 rounded-3">
					<div class="row position-relative">
						<!-- Action box -->
						<div class="col-11 mx-auto position-relative">
							<div class="row align-items-center">
								<!-- Title -->
								<div class="col-lg-7">
									<h3 class="text-white">Become an Instructor!</h3>
									<p class="text-white mb-3 mb-lg-0">Speedily say has suitable disposal add boy. On forth doubt miles of child. Exercise joy man children rejoiced. Yet uncommonly his ten who diminution astonished.</p>
								</div>
								<!-- Content and input -->
								<div class="col-lg-5 text-lg-end">
									<a href="{% url 'myapp:contact' %}" class="btn btn-outline-warning mb-0 text-white">Start Teaching Today</a>
								</div>
							</div>
						</div>
					</div> <!-- Row END -->
				</div>
			</div>
		</div>
  </div>



  <div class="container my-5">
    <h2 class="text-center my-5">Latest Blog</h2>
    <div class="row mb-2">
    {% for allblog in allblog %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Online Tutorial</strong>
          <h3 class="mb-0">{{allblog.blog_title}}</h3>
          <div class="mb-1 text-muted">{{allblog.created_at|date}}</div>
          <p class="card-text mb-auto">{{allblog.blog_about|safe|truncatechars:54}}</p>
          <a href="{% url 'myapp:blogs_detail' allblog.slug %}" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          {% comment %} <img src="{{allblog.thumbnail.url}}" alt="" srcset=""> {% endcomment %}

        </div>
      </div>
    </div>
   {% endfor %} 
  </div>
  </div>
  <div class="col-12 text-center my-4">
                        <a class="btn btn-primary rounded-pill py-3 px-5 text-white" href="{% url 'myapp:blogapp' %}">Browse More</a>
                    </div>
       
<a href="#" class="btn btn-lg  btn-lg-square rounded-circle back-to-top "><i class="fa-solid fa-circle-arrow-up fa-sm" style="color: #8f13c9;"></i></a>
{% endblock content %}

templates/premium.html
{% extends 'base.html' %}
{% block title %}Premium{% endblock title %}
{% block content %}
<div class="container">
              <div class="row">
                <div class="col-md-6 mx-auto">
                  <h2 class="text-center fs-1 mx-auto">Premium Course</h2>
                  <p class="mb-0 text-center mx-auto">Explore couses with most helpful tools.</p>
                </div>
              </div>
            </div>
            <div class="container">
            <div id="new" class="tab-pane fade show p-0 active">
              <div class="container">
                <div class="row g-4">
                  {% for premium in premium %}
                    <div class="col-lg-4 col-md-6 shadow">
                        <div class="product-item">
                            <div class="position-relative bg-light">
                                <img class="img-fluid w-100" src="{{premium.course_thumbnail.url}}" alt="">
                                <div class="bg-danger rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">-{{premium.course_discount}}%</div>
                            </div>
                            <div class="text-center p-4">
                                <h4 class="d-block  mb-2" href="">{{premium.course_title}}</h4>
                                <h6>{{premium.course_about}}</h6>
                                <span class="text-primary me-1">₹{{premium.discount}}</span>
                                <span class="text-body text-decoration-line-through">Rs.{{premium.course_price}}</span>
                            </div>
                            <div class="d-flex border-top">
                                    <a class="text-decoration-none p-3 text-center mx-auto" href="{% url 'premium:overview' premium.course_slug %}"><i class="fa fa-eye text-primary me-2"></i>View detail</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    </div>
                    </div>
                    </div>
                    </div>

{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% block title %}Search | {{query}}{% endblock title %}
{% block content %}
{% comment %} {% if query %}
<h3 class="mx-4">Search:{{query}}</h3>

<div class="container mx-auto">
<div class="d-inline-flex flex-wrap">
{% for course in searchfilter %}
<div class="d-flex mx-4 card mt-2 rounded-2x1" style="width: 19rem;">
  <img src="{{course.course_thumbnail.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{course.course_title}}</h5>
    <p class="card-text">{{course.course_about}}</p>
    <a href="{% url 'myapp:cours' course.course_slug %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
  {% endfor %}
</div>
  </div>
{% else %}
<h1 class="text-center">Not found</h1>
{% endif %} {% endcomment %}

{% if searchfilter|length < 1 %}
<div class="row">
  <div class="col-md-8 mx-auto">

    <div class="container my-5 card-title">
  <img src="/image/sorry.png" align="center">
<p>
Your search - {{ query }} - did not match any documents.<br><br>

Suggestions:<br><br>

Make sure that all words are spelled correctly.<br>
<ul>
<li>Try different keywords.</li>
<li>Try more general keywords.</li>
<li>Try fewer keywords.</li>
</p>
</div>

</div>
</div>
{% else %}
{% endif %}
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-10">
          {% for course in searchfilter %}
            <div class="row p-2 bg-white border rounded">
                <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image" src="{{course.course_thumbnail.url}}"></div>
                <div class="col-md-6 mt-1">
                    <h5>{{course.course_title}}</h5>
                    {% comment %} <div class="d-flex flex-row">
                        <div class="ratings mr-2"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div><span>310</span>
                    </div> {% endcomment %}
                    {% comment %} <div class="mt-1 mb-1 spec-1"><span>100% cotton</span><span class="dot"></span><span>Light weight</span><span class="dot"></span><span>Best finish<br></span></div>
                    <div class="mt-1 mb-1 spec-1"><span>Unique design</span><span class="dot"></span><span>For men</span><span class="dot"></span><span>Casual<br></span></div> {% endcomment %}
                    <p class="text-justify text-truncate para mb-0">{{course.course_about|truncatechars:130}}<br><br></p>
                </div>
                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                    <h6 class="text-success">Free</h6>
                    <div class="d-flex flex-column mt-4"><a href="{% url 'myapp:cours' course.course_slug %}" class="text-white btn btn-primary btn-sm" type="button">Details</a></div>
                </div>
            </div>
              {% endfor %}
          {% for search_premium in search_premium %}
            <div class="row p-2 bg-white border rounded">
                <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image" src="{{search_premium.course_thumbnail.url}}"></div>
                <div class="col-md-6 mt-1">
                    <h5>{{search_premium.course_title}}</h5>
                    {% comment %} <div class="d-flex flex-row">
                        <div class="ratings mr-2"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div><span>310</span>
                    </div> {% endcomment %}
                    {% comment %} <div class="mt-1 mb-1 spec-1"><span>100% cotton</span><span class="dot"></span><span>Light weight</span><span class="dot"></span><span>Best finish<br></span></div>
                    <div class="mt-1 mb-1 spec-1"><span>Unique design</span><span class="dot"></span><span>For men</span><span class="dot"></span><span>Casual<br></span></div> {% endcomment %}
                    <p class="text-justify text-truncate para mb-0">{{course.course_about|truncatechars:130}}<br><br></p>
                </div>
                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                    <div class="d-flex flex-row align-items-center">
                        <h4 class="mr-1">Rs.{{search_premium.discount}}</h4><span class="strike-text text-decoration-line-through">Rs.{{search_premium.course_price}}</span>
                    </div>
                    <h6 class="text-success">Premium Course</h6>
                    <div class="d-flex flex-column mt-4"><a href="{% url 'premium:overview' search_premium.course_slug %}" class="text-white btn btn-primary btn-sm" type="button">Details</a></div>
                </div>
            </div>
              {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}